# Generated by Django 3.2.23 on 2023-12-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='titile',
            new_name='title',
        ),
    ]
